<?php

namespace Thorazine\Geo\Enums;

enum Country: string
{
    use EnumTrait;

    case AF = 'AF'; // Afghanistan
    case AX = 'AX'; // Åland
    case AL = 'AL'; // Albanië
    case DZ = 'DZ'; // Algerije
    case VI = 'VI'; // Amerikaanse Maagdeneilanden
    case AS = 'AS'; // Amerikaans-Samoa
    case AD = 'AD'; // Andorra
    case AO = 'AO'; // Angola
    case AI = 'AI'; // Anguilla
    case AQ = 'AQ'; // Antarctica
    case AG = 'AG'; // Antigua en Barbuda
    case AR = 'AR'; // Argentinië
    case AM = 'AM'; // Armenië
    case AW = 'AW'; // Aruba
    case AU = 'AU'; // Australië
    case AZ = 'AZ'; // Azerbeidzjan
    case BS = 'BS'; // Bahama's
    case BH = 'BH'; // Bahrein
    case BD = 'BD'; // Bangladesh
    case BB = 'BB'; // Barbados
    case BE = 'BE'; // België
    case BZ = 'BZ'; // Belize
    case BJ = 'BJ'; // Benin
    case BM = 'BM'; // Bermuda
    case BT = 'BT'; // Bhutan
    case BO = 'BO'; // Bolivia
    case BQ = 'BQ'; // Bonaire, Sint Eustatius en Saba
    case BA = 'BA'; // Bosnië en Herzegovina
    case BW = 'BW'; // Botswana
    case BV = 'BV'; // Bouveteiland
    case BR = 'BR'; // Brazilië
    case VG = 'VG'; // Britse Maagdeneilanden
    case IO = 'IO'; // Brits Indische Oceaanterritorium
    case BN = 'BN'; // Brunei
    case BG = 'BG'; // Bulgarije
    case BF = 'BF'; // Burkina Faso
    case BI = 'BI'; // Burundi
    case KH = 'KH'; // Cambodja
    case CA = 'CA'; // Canada
    case CF = 'CF'; // Centraal-Afrikaanse Republiek
    case CL = 'CL'; // Chili
    case CN = 'CN'; // China
    case CX = 'CX'; // Christmaseiland
    case CC = 'CC'; // Cocoseilanden
    case CO = 'CO'; // Colombia
    case KM = 'KM'; // Comoren
    case CG = 'CG'; // Congo-Brazzaville
    case CD = 'CD'; // Congo-Kinshasa
    case CK = 'CK'; // Cookeilanden
    case CR = 'CR'; // Costa Rica
    case CU = 'CU'; // Cuba
    case CW = 'CW'; // Curaçao
    case CY = 'CY'; // Cyprus
    case DK = 'DK'; // Denemarken
    case DJ = 'DJ'; // Djibouti
    case DM = 'DM'; // Dominica
    case DO = 'DO'; // Dominicaanse Republiek
    case DE = 'DE'; // Duitsland
    case EC = 'EC'; // Ecuador
    case EG = 'EG'; // Egypte
    case SV = 'SV'; // El Salvador
    case GQ = 'GQ'; // Equatoriaal-Guinea
    case ER = 'ER'; // Eritrea
    case EE = 'EE'; // Estland
    case ET = 'ET'; // Ethiopië
    case FO = 'FO'; // Faeröer
    case FK = 'FK'; // Falklandeilanden
    case FJ = 'FJ'; // Fiji
    case PH = 'PH'; // Filipijnen
    case FI = 'FI'; // Finland
    case FR = 'FR'; // Frankrijk
    case TF = 'TF'; // Franse Zuidelijke en Antarctische Gebieden
    case GF = 'GF'; // Frans-Guyana
    case PF = 'PF'; // Frans-Polynesië
    case GA = 'GA'; // Gabon
    case GM = 'GM'; // Gambia
    case GE = 'GE'; // Georgië
    case GH = 'GH'; // Ghana
    case GI = 'GI'; // Gibraltar
    case GD = 'GD'; // Grenada
    case GR = 'GR'; // Griekenland
    case GL = 'GL'; // Groenland
    case GP = 'GP'; // Guadeloupe
    case GU = 'GU'; // Guam
    case GT = 'GT'; // Guatemala
    case GG = 'GG'; // Guernsey
    case GN = 'GN'; // Guinee
    case GW = 'GW'; // Guinee-Bissau
    case GY = 'GY'; // Guyana
    case HT = 'HT'; // Haïti
    case HM = 'HM'; // Heard en McDonaldeilanden
    case HN = 'HN'; // Honduras
    case HU = 'HU'; // Hongarije
    case HK = 'HK'; // Hongkong
    case IE = 'IE'; // Ierland
    case IS = 'IS'; // IJsland
    case IN = 'IN'; // India
    case ID = 'ID'; // Indonesië
    case IQ = 'IQ'; // Irak
    case IR = 'IR'; // Iran
    case IL = 'IL'; // Israël
    case IT = 'IT'; // Italië
    case CI = 'CI'; // Ivoorkust
    case JM = 'JM'; // Jamaica
    case JP = 'JP'; // Japan
    case YE = 'YE'; // Jemen
    case JE = 'JE'; // Jersey
    case JO = 'JO'; // Jordanië
    case KY = 'KY'; // Kaaimaneilanden
    case CV = 'CV'; // Kaapverdië
    case CM = 'CM'; // Kameroen
    case KZ = 'KZ'; // Kazachstan
    case KE = 'KE'; // Kenia
    case KG = 'KG'; // Kirgizië
    case KI = 'KI'; // Kiribati
    case UM = 'UM'; // Kleine afgelegen eilanden van de Verenigde Staten
    case KW = 'KW'; // Koeweit
    case OO = 'OO'; // Kosovo
    case HR = 'HR'; // Kroatië
    case LA = 'LA'; // Laos
    case LS = 'LS'; // Lesotho
    case LV = 'LV'; // Letland
    case LB = 'LB'; // Libanon
    case LR = 'LR'; // Liberia
    case LY = 'LY'; // Libië
    case LI = 'LI'; // Liechtenstein
    case LT = 'LT'; // Litouwen
    case LU = 'LU'; // Luxemburg
    case MO = 'MO'; // Macau
    case MK = 'MK'; // Macedonië
    case MG = 'MG'; // Madagaskar
    case MW = 'MW'; // Malawi
    case MV = 'MV'; // Maldiven
    case MY = 'MY'; // Maleisië
    case ML = 'ML'; // Mali
    case MT = 'MT'; // Malta
    case IM = 'IM'; // Man
    case MA = 'MA'; // Marokko
    case MH = 'MH'; // Marshalleilanden
    case MQ = 'MQ'; // Martinique
    case MR = 'MR'; // Mauritanië
    case MU = 'MU'; // Mauritius
    case YT = 'YT'; // Mayotte
    case MX = 'MX'; // Mexico
    case FM = 'FM'; // Micronesia
    case MD = 'MD'; // Moldavië
    case MC = 'MC'; // Monaco
    case MN = 'MN'; // Mongolië
    case ME = 'ME'; // Montenegro
    case MS = 'MS'; // Montserrat
    case MZ = 'MZ'; // Mozambique
    case MM = 'MM'; // Myanmar
    case NA = 'NA'; // Namibië
    case NR = 'NR'; // Nauru
    case NL = 'NL'; // Nederland
    case NP = 'NP'; // Nepal
    case NI = 'NI'; // Nicaragua
    case NC = 'NC'; // Nieuw-Caledonië
    case NZ = 'NZ'; // Nieuw-Zeeland
    case NE = 'NE'; // Niger
    case NG = 'NG'; // Nigeria
    case NU = 'NU'; // Niue
    case MP = 'MP'; // Noordelijke Marianen
    case KP = 'KP'; // Noord-Korea
    case NO = 'NO'; // Noorwegen
    case NF = 'NF'; // Norfolk
    case UG = 'UG'; // Oeganda
    case UA = 'UA'; // Oekraïne
    case UZ = 'UZ'; // Oezbekistan
    case OM = 'OM'; // Oman
    case AT = 'AT'; // Oostenrijk
    case TL = 'TL'; // Oost-Timor
    case PK = 'PK'; // Pakistan
    case PW = 'PW'; // Palau
    case PS = 'PS'; // Palestina
    case PA = 'PA'; // Panama
    case PG = 'PG'; // Papoea-Nieuw-Guinea
    case PY = 'PY'; // Paraguay
    case PE = 'PE'; // Peru
    case PN = 'PN'; // Pitcairneilanden
    case PL = 'PL'; // Polen
    case PT = 'PT'; // Portugal
    case PR = 'PR'; // Puerto Rico
    case QA = 'QA'; // Qatar
    case RE = 'RE'; // Réunion
    case RO = 'RO'; // Roemenië
    case RU = 'RU'; // Rusland
    case RW = 'RW'; // Rwanda
    case BL = 'BL'; // Saint-Barthélemy
    case KN = 'KN'; // Saint Kitts en Nevis
    case LC = 'LC'; // Saint Lucia
    case PM = 'PM'; // Saint-Pierre en Miquelon
    case VC = 'VC'; // Saint Vincent en de Grenadines
    case SB = 'SB'; // Salomonseilanden
    case WS = 'WS'; // Samoa
    case SM = 'SM'; // San Marino
    case SA = 'SA'; // Saoedi-Arabië
    case ST = 'ST'; // Sao Tomé en Principe
    case SCH = 'SCH'; // Schotland
    case SN = 'SN'; // Senegal
    case RS = 'RS'; // Servië
    case SC = 'SC'; // Seychellen
    case SL = 'SL'; // Sierra Leone
    case SG = 'SG'; // Singapore
    case SH = 'SH'; // Sint-Helena, Ascension en Tristan da Cunha
    case MF = 'MF'; // Sint-Maarten
    case SX = 'SX'; // Sint Maarten
    case SI = 'SI'; // Slovenië
    case SK = 'SK'; // Slowakije
    case SD = 'SD'; // Soedan
    case SO = 'SO'; // Somalië
    case ES = 'ES'; // Spanje
    case SJ = 'SJ'; // Spitsbergen en Jan Mayen
    case LK = 'LK'; // Sri Lanka
    case SR = 'SR'; // Suriname
    case SZ = 'SZ'; // Swaziland
    case SY = 'SY'; // Syrië
    case TJ = 'TJ'; // Tadzjikistan
    case TW = 'TW'; // Taiwan
    case TZ = 'TZ'; // Tanzania
    case TH = 'TH'; // Thailand
    case TG = 'TG'; // Togo
    case TK = 'TK'; // Tokelau
    case TO = 'TO'; // Tonga
    case TT = 'TT'; // Trinidad en Tobago
    case TD = 'TD'; // Tsjaad
    case CZ = 'CZ'; // Tsjechië
    case TN = 'TN'; // Tunesië
    case TR = 'TR'; // Turkije
    case TM = 'TM'; // Turkmenistan
    case TC = 'TC'; // Turks- en Caicoseilanden
    case TV = 'TV'; // Tuvalu
    case UY = 'UY'; // Uruguay
    case VU = 'VU'; // Vanuatu
    case VA = 'VA'; // Vaticaanstad
    case VE = 'VE'; // Venezuela
    case AE = 'AE'; // Verenigde Arabische Emiraten
    case US = 'US'; // Verenigde Staten
    case GB = 'GB'; // Verenigd Koninkrijk
    case VN = 'VN'; // Vietnam
    case WF = 'WF'; // Wallis en Futuna
    case EH = 'EH'; // Westelijke Sahara
    case BY = 'BY'; // Wit-Rusland
    case ZM = 'ZM'; // Zambia
    case ZW = 'ZW'; // Zimbabwe
    case ZA = 'ZA'; // Zuid-Afrika
    case GS = 'GS'; // Zuid-Georgia en de Zuidelijke Sandwicheilanden
    case KR = 'KR'; // Zuid-Korea
    case SS = 'SS'; // Zuid-Soedan
    case SE = 'SE'; // Zweden
    case CH = 'CH'; // Zwitserland


    protected static function translationPath(): string
    {
        return 'countries.';
    }
}
